server:
  port: 0
  forward-headers-strategy: framework

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    active: dev
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # 여기에 feign 설정을 추가
  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
      product-service:
        url: http://localhost:8000/api/v1/product-service
      review-service:
        url: http://localhost:8000/api/v1/review-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
jwt:
  secret: ${JWT_SECRET}
  expiration: 604800000 # 추후에 바꾸기 -> 1800000
  refresh-expiration: 604800000

# swagger
springdoc:
  packages-to-scan: com.momnect.userservice
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

# 파일 서비스 URL 설정
ftp:
  file-server-url: ${FTP_SERVER_URL}