apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: momnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: junga970/product-service:dev-1
          envFrom:
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: momnect
spec:
  selector:
    app: product-service
  clusterIP: None   # Headless (Eureka 의존)
  ports:
    - port: 80
      targetPort: 80   # placeholder
