apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: momnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
        - name: websocket-service
          image: junga970/websocket-service:dev-1
          ports:
            - containerPort: 8085
          envFrom:
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: momnect
spec:
  selector:
    app: websocket-service
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085   # EC2 외부에서도 접근 가능
  type: NodePort
